### ISSUE TITLE
Cannot generate baseline file

### ISSUE THREAD

**Issue by pglebocki** [arturbosch/detekt#1044]
## Expected Behavior
./gradlew detektBaseline should generate baseline.xml file

## Current Behavior
command above says what --baseline parameter is required, but when I passing this parameter then it prints that parameter is unknown

## Your Environment
using RC.7

**Comment by pglebocki** [comment]
Not related.

**Comment by Liverm0r** [comment]
I have the same issue with RC9. How did you resolve this?

**Comment by marschwar** [comment]
In order to create a baseline using gradle please create a detekt closure in your build.gradle and specify the baseline there.

```
detekt {
    baseline = file("path/to/baseline.xml")
}
```

A documentation on how to use the groovy dsl can be found in the [groovydsl.md](https://github.com/arturbosch/detekt/blob/master/docs/pages/gettingstarted/groovydsl.md#options-for-detekt-configuration-closure).

**Comment by Liverm0r** [comment]
Thank you for the answer. The problem was that I din't specify the plugin for subprojects.
```
subprojects {
    apply {
        plugin("io.gitlab.arturbosch.detekt")
    }
    detekt {
        //...
    }
}
```
