### ISSUE TITLE
DetektCheck only for git commiting files?

### ISSUE THREAD

**Issue by wypa** [arturbosch/detekt#1057]
Hi,
i've setup my Android Gradle project with detektCheck and a precommit hook in git//hooks folder. So every time i make a commit, it will start detektCheck. The check runs against whole project and not against the files I'd like to commit. Is it possible to run it only against commiting files?

**Comment by schalkms** [comment]
You stated a solution to your problem. Let me just explain your problem.
I assume that you want to know how many new code smells are introduced by your latest commit.
Since you don't want to compare your report manually every time, you can use Sonarqube to make it easier. Sonarqube shows that information right away. Please take a look [here].(https://i.stack.imgur.com/wDo4q.png)
There's also a Sonarqube plugin for detekt available. 
https://github.com/arturbosch/sonar-kotlin

HTH
