### ISSUE TITLE
Question: drop kotlin-dsl dependency from Gradle plugin?

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1286]
kotlin-dsl has a set of Kotlin dependencies which are bundled with Gradle (currently Kotlin 1.2.61). The detekt Gradle plugin is written in Kotlin, but because it has the `kotlin-dsl` plugin as a dependency, hte plugin must be written in the same version of Kotlin.

In the plugin it looks like the only kotlin-dsl feature currently used is the `property` extension function: https://github.com/gradle/kotlin-dsl/blob/v1.0-RC6/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/ObjectFactoryExtensions.kt#L52-L58

Could easily copy the extension function or just use a slightly less pleasant syntax to create a Property, and then the plugin wouldn't be held back to whichever version of Kotlin Gradle bundles.

kotlin-dsl for plugin development. Should it stay or should it go?

**Comment by marschwar** [comment]
> ...but  because it has the kotlin-dsl plugin as a dependency, hte plugin must be written in the same version of Kotlin
To be honest I do not completely understand why this is the case but I agree that using the kotlin-dsl plugin does not provide much of a benefit (or we are just not using it correctly/enough).

Even though it turns out it a few other things than the `property` function had to be changed it was rather straight forward to remove the plugin.

https://github.com/marschwar/detekt/commit/fd2b03204c414b58cbd2dcd5c5b8676280d7f096

**Comment by arturbosch** [comment]
Idk, is it recommended to stay on the same version?
@marschwar branch looks good though, even prettier functions now :D
