### ISSUE TITLE
Option to only build reports on failure

### ISSUE THREAD

**Issue by maragues-kolibree** [arturbosch/detekt#1318]
## Expected Behavior

Reports are built only on failure

## Current Behavior

Reports are always built

## Context

I'd like to reduce the execution time as much as possible, every second counts in a CI pipeline. It'd necessary to profile the time it takes to build a success report (mostly empty). 

- If it's really small (<100ms, for example), this issue can be closed.

- If it's over that value, it'd be worth adding the option.

I'm running a multi-module project that's building 15-20 reports each time I run _detekt_, so even if it's 500ms, it adds to ~10 seconds per pipeline run, which amounts to a lot during a week.

**Comment by vanniktech** [comment]
Reports should always be built and if they don't contain any warnings / errors be empty. Every other tool does it like this too.

Also, measure before creating an issue. No one will measure this for you.

**Comment by maragues-kolibree** [comment]
You are probably right on the parallel making this meaningless, I'll close the issue

**Comment by arturbosch** [comment]
Hey, I can confirm that all the report generating stuff is under < 100ms. Been there measured it some time ago :D. If you are still concerned you can deactivate all `Console-` and `OutputReport`'s in the configuration file, then they are all skipped and measure your time.
The 500ms overhead is due to how the gradle plugin works. For each module detekt is invoked which need to setup the kotlin compiler. This is really huge. For a super duper multi project gradle build I would consider writing your own detekt task which calls it only for the whole project.
