### ISSUE TITLE
Adding S.O.L.I.D. principles to configuration...

### ISSUE THREAD

**Issue by urosjarc** [arturbosch/detekt#1381]
I would really like to somehow add [SOLID principles](https://en.wikipedia.org/wiki/SOLID) to this tool...
This would really help new kotlin developers to get the best practice, and also this feature would make this tool really popular too because SOLID principles are getting recognized more and more as good practice for software development. practice.

I don't know detekt inside out so I would like to ask contributors what would be the best way to make this happened.

Thank you!

**Comment by arturbosch** [comment]
Hey, 
one way would be to find subsets of rules which clearly help enforcing these principles.
For example SRP:
- TooManyFunctions, LargeClass, LongMethod, LongParameterList, ComplexMethod etc

**Comment by schalkms** [comment]
I don't think that static analysis can determine if the SOLID principles are respected.
To verify each principle the rule needs to formally define the meaning and semantics. Then every valid Kotlin code needs to be checked against this. How would you formalize the notion of the SOLID principles?
However, there are some rules which help to comply with SOLID.

I don't know any static analysis tool that provides this functionality.
I favor to close this issue because of the mentioned limitations.

@urosjarc 
if you want to improve Detekt and push it towards linting more issues regarding to SOLID we could use help here #7 #418 
Especially metrics defined [here](https://www.hanselman.com/blog/content/binary/NDepend%20metrics%20placemats%201.1.pdf) would be a nice addition to detekt.

**Comment by urosjarc** [comment]
This issue is joust for exploration and general discussion, let's consider it brainstorming. I have not discovered lint tool that would do something similar, but somewhere we have to start...

I would really dislike closing this issue because I would really like to gather more advises about this request that I have from more experienced people...

Thank you so much for the links that you have provided I will take a close look into it.

**Comment by schalkms** [comment]
Thank you for taking the time to discuss this.
It is very very hard to formally define a rule (call it `SRPViolator`) which violates the SRP. Please keep in mind that this has to work for every valid piece of Kotlin code. One would run into many false positives with this approach. Therefore, this approach makes no sense to me.

I'd love to have more **standalone** rules which help to adhere to SOLID. If you have *specific* ideas for rules, please feel free to create an issue explaining the meaning of it. Usually this idea gets flagged with the appropriate tags. If the community sees a need for the rule, it gets implemented.

The thing with this *generic* issue is that is very hard for someone to complete this issue with a PR.
Furthermore, one could interpret a lot of things into it. Hence, it does not help to complete this issue either.

**Comment by urosjarc** [comment]
Hm, I guess I should then break this issue into separate features that should be more easily implemented, @schalkms you are quite right! I should break this issue into separate principles furthermore dived them to separate rules that would be more easy to implement... I suggest that this issue is moved to the backlog (or whatever), and I will link further issues (feature requests) to this issue.... Does this sound good for you guys?

**Comment by schalkms** [comment]
@urosjarc
Good. I think we are on the same page now.
Since you asked for feedback and opinions from the community this issue stays open for some days.

**Comment by schalkms** [comment]
Closed due to the broad range of this topic. Further discussion can go on in the linked issues.
