### ISSUE TITLE
Drop @author tags

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1627]
I hope this isn't too controversial...!

I propose that the `@author` KDoc tags be removed from the code base, for the following reasons:

* They're out of date
* Full history available in git log
* More useful to use `git blame` to find out who changed what, since the current author tags are out of date
* They're only shown in source code
* README is already used to highlight some major contributors

I definitely don't want to take away form anyone's contributions (especially from @arturbosch!) I'm just not sure the author tag is the best way to record them.

**Comment by vanniktech** [comment]
There's a Git history for exactly this particular use case.

**Comment by schalkms** [comment]
I agree with both of you.

**Comment by arturbosch** [comment]
I've got the idea from a blog post of Yegor Bugayenko to highlight contributors who spent their free time to work on this project. That's why I have the contributors list. 
My author tag appeared everywhere due to me being lazy to turn it off in IntelliJ kdoc template generation.
I agree with you that it's redundant with git's log and the contribution list is the place to highlight major contribution from other users +1

**Comment by 3flex** [comment]
Cool! I think instead of just removing the tags, a new rule would be good, to allow configuration of forbidden KDoc tags. Then run over the codebase and see if it picks them all up.
