### ISSUE TITLE
Unable to use "exclude" in 1.0.0-RC15 with groovy dsl

### ISSUE THREAD

**Issue by dimsuz** [arturbosch/detekt#1712]
## Expected Behavior
When using `exlude` instead of deprecated `filters`, gradle Sync finishes successfully in IDE

## Observed Behavior
Gradle Sync finishes with an error:

> Could not set unknown property 'exclude' for object of type io.gitlab.arturbosch.detekt.extensions.DetektExtension.

## Steps to Reproduce
I have the following in my rootproject `build.gradle`:
```
plugins {
  id "io.gitlab.arturbosch.detekt" version "1.0.0-RC15"
}

detekt {
  toolVersion = '1.0.0-RC15'
  config = files(
    rootProject.file("detekt-config.yml")
  )
  exclude = "**/resources/**"
  exclude = "**/build/**"

  reports {
    xml.enabled = false
    html.enabled = false
  }
}
```

But if I revert back to `filters`, it works just ok:
```
  filters = "**/resources/**,**/build/**"
```
Sync is OK this time

I also tried `exclude "**resources**` (without `=`) - doesn't work either.

**Comment by arturbosch** [comment]
Please try the groovy equivalent of groovy dsl for
```
tasks.withType<Detekt> {
    exclude("resources/")
    exclude("build/")
}
```
outside the detekt closure.

@3flex is there any change we can bring `exclude` and `include` into the `DetektExtension`?

**Comment by arturbosch** [comment]
It seems that this methods just delete the parameters and are only used when `source` is called internally. We should allow these in the extension and delegate then oursselves in the detekt task.

**Comment by 3flex** [comment]
@arturbosch You can do that but extra code and deviates from how Gradle's code quality plugins are configured.

Also this isn't a regression, it's designed to be configured this way - the "filters" parameter was removed from the extension and now includes/excludes should be set on the task... Are you saying this doesn't work?

**Comment by arturbosch** [comment]
@3flex it does work.
But its a bit inconvenient to have to specify the excludes and includes outside the detekt extension.
It's like you have two blocks for detekt instead of one.
But I haven't used the other code quality plugins much ... maybe that's why I looks strange to me ...

**Comment by dimsuz** [comment]
As a gradle-fu junior I would vote for support for this on the extension. Or at least mentioning explicitly in the `README.md` that two config blocks are now needed.

Also I can't figure out how to do this in groovy DSL. I try:

```
tasks.withType(Detekt) {
  exclude = ...
}
```
(similar to `tasks.withType(Jar)` which I managed to google quickly)

But this causes gradle to complain that it doesn't know any `Detect` class or entity. Detekt plugin is specified in the same file, detekt extension is there too and it works, but this block above doesn't.

If anyone would help me here, I would be grateful.

**Comment by 3flex** [comment]
Try `tasks.withType(io.gitlab.arturbosch.detekt.Detekt)` - the task type isn't automatically imported for third party task types (`Jar` works because it's included with Gradle).

Also note that `resources` and `build` dirs are already automatically excluded since the default input path is `[src/main/java, src/main/kotlin]` for the `detekt` task, so depending what you want to exclude you might not need to manually configure any excludes at all.

@arturbosch I think this is a documentation issue rather than a problem with the plugin. Adding support for includes/excludes on the extension may not be OK... what happens when the includes/excludes set on the extension conflict with includes/excludes set on the task? Also as each task is a SourceTask now (to support auto-creation of a task for each SourceSet) each auto-created task only includes source files in the SourceSet. For example `detektMain` task doesn't include any test sources, and automatically excludes build and resource directories. Setting includes/excludes on the extension instead of individual tasks doesn't make as much sense in that scenario.

**Comment by arturbosch** [comment]
@3flex you're right, we need to update the docs.
