### ISSUE TITLE
Detekt Gradle plugin fails when applied from gradle script file

### ISSUE THREAD

**Issue by WonderCsabo** [arturbosch/detekt#1770]
## Expected Behavior
The Detekt Gradle plugin should be able to be applied from a Gradle script file.

## Observed Behavior
When applied from a script file, the plugin fails with the following error:
```java
Caused by: org.gradle.api.GradleException: Kotlin source set not found. Please report on detekt's issue tracker
        at io.gitlab.arturbosch.detekt.DetektPlugin.registerDetektTask(DetektPlugin.kt:85)
        at io.gitlab.arturbosch.detekt.DetektPlugin.access$registerDetektTask(DetektPlugin.kt:25)
        at io.gitlab.arturbosch.detekt.DetektPlugin$registerDetektTasks$1$1$1.execute(DetektPlugin.kt:48)
        at io.gitlab.arturbosch.detekt.DetektPlugin$registerDetektTasks$1$1$1.execute(DetektPlugin.kt:25)
```

## Steps to Reproduce
Clone the repo: https://github.com/WonderCsabo/detektTest
Open the folder and run `./gradlew clean`

## Context
We have common build logic extracted to standalone .gradle script files. We are applying the detekt plugin in those files. It worked well until RC14. However it broke after that with error message above.

## Your Environment

* Version of detekt used: 1.0.0-RC16
* Version of Gradle used (if applicable): 5.4.1
* Operating System and version: MacOS 10.14.4

**Comment by 3flex** [comment]
Try removing the `afterEvaluate` block - the plugin should just be applied directly, so add the `apply from: "detekt.gradle"` statement directly after the other `apply plugin` statements.

If that doesn't fix it I'll take a closer look.

**Comment by WonderCsabo** [comment]
@3flex thanks for the reply! Unfortunately moving the statement results in the same error.

**Comment by 3flex** [comment]
If I remove this block:
```groovy
afterEvaluate {
    apply from: "detekt.gradle"
}
```

Then add this block (copied directly from the referenced file):
```groovy
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC16"
    }
}

apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin
```

Then the build works. But just referencing the script with `apply from` doesn't. Gradle doesn't simply include the script in the build script, there's some extra logic applied, so while it's expected this would work it won't.

I'm not sure what change was made in the plugin to cause this to stop working and I don't know what can be done to address it, since the problem is with Gradle's behaviour. An alternative could be to apply the detekt plugin using the plugins DSL then use `apply from` to apply the detekt configuration from a separate file, that should work, though I know it's an extra couple of lines in the build script and it means the detekt plugin can't be applied then configured from within a single file.

Which other plugins are you including in this manner?

**Comment by WonderCsabo** [comment]
I think [this](https://github.com/arturbosch/detekt/commit/98cb54fe2c64a54bf0df930f96f9b013329bb3bc#diff-a34e9ed62f396676b3dcbfcd703292a9R87) change introduced the problem for us.

Currently we apply the Checkstyle, PMD, Spotbugs and detekt Gradle plugins this way. To give some context, we extracted our code quality configuration to standalone .gradle files, so we can apply it to several projects.

**Comment by 3flex** [comment]
Definitely that commit would have caused the problem, but my take is that since Gradle doesn't offer an "include file" option, the fact that "apply from" used to work is more a happy accident than something properly supported by Gradle (and therefore detekt).

You can see for example that Uber uses the technique I mentioned of applying the plugin then applying the plugin's config over two lines in their Android app template: https://github.com/uber/android-template/blob/master/build.gradle

I think this is the way to go, though open to suggestions on how to make this work like it used to if it's not complicated to implement.

**Comment by lwasyl** [comment]
Gradle supports including from file, and it's exactly what `apply from:` is. Afaik the problem is that technically the other `.gradle` file is a plugin (it's not like macro substitution), so buildscript classpath logic is pretty tricky. I don't understand it fully so I can't say exactly what's wrong. 

What I do know is that having `buildcript` blocks in files other than `build.gradle` is discouraged. So what you can do instead is to have relevant buildscript (repository and classpath) dependencies in your root project's `build.gradle` (so it's available to all subprojects) and apply the plugin using its string ID as defined [here](https://github.com/arturbosch/detekt/blob/master/detekt-gradle-plugin/build.gradle.kts#L43).

You'll encounter another problem then, and it's that `jcommander` dependency is not available. I've been able to work around this by adding `gradlePluginPortal()` to `repositories` block (the root one, not `buildscript/repositories`). I don't have time to dive in to say exactly why it's needed, but I believe it shouldn't be required. I guess there's something non-idiomatic in Detekt's gradle plugin implementation and where it takes dependencies from.

Here's diff on your project that made detekt for for me locally. The only unfortunate and surprising thing for me is that need for plugin portal dependency :\ 
```diff
diff --git a/build.gradle b/build.gradle
index f00dc52..a4c2fea 100644
--- a/build.gradle
+++ b/build.gradle
@@ -10,11 +10,13 @@ buildscript {
     
     dependencies {
         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.41'
+        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC16"
     }
 }
 
 repositories {
     mavenCentral()
+    gradlePluginPortal()
 }
 
 apply plugin: 'java-library'
diff --git a/detekt.gradle b/detekt.gradle
index daec529..7183b02 100644
--- a/detekt.gradle
+++ b/detekt.gradle
@@ -1,10 +1 @@
-buildscript {
-    repositories {
-        gradlePluginPortal()
-    }
-    dependencies {
-        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC16"
-    }
-}
-
-apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin
\ No newline at end of file
+apply plugin: "io.gitlab.arturbosch.detekt"
```

**Comment by 3flex** [comment]
@WonderCsabo did you find some of the suggestions helpful? I know they don't directly resolve your issue but should get quite close.

**Comment by WonderCsabo** [comment]
Thanks for getting back to me.

It could work, however i ran into another problem. In our real build script, we register custom detekt tasks:
```groovy
tasks.register("someDetektTask", io.gitlab.arturbosch.detekt.Detekt) { ... }
```
This will result in:
> groovy.lang.MissingPropertyException: Could not get unknown property 'io' for project ':app' of type org.gradle.api.Project.

**Comment by lwasyl** [comment]
@WonderCsabo I guess you're trying to register the task in different `*.gradle` file than root build gradle file (and also not on `build.gradle`, but an included script?). Either way typically things would start working if you repeat buildscript block and Detekt dependency in that file, so that `io.gitlab...Detekt` class is recognized.
Another option would be to create those tasks from root build.gradle, where buildscript dependency is already added (for example by using `subprojects { }` closure).
It's difficult to figure out exactly what would be the best way to approach this without knowing exact structure (which files do what) of what you're trying to achieve

**Comment by WonderCsabo** [comment]
@lwasyl thanks for the answer! If i add

`classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC16"`
to the root build gradle (with the needed repository)

and change to `apply plugin: "io.gitlab.arturbosch.detekt"` in the separate build script file, but leave the `buildscript` block in that file, it works. 

However now our Android projects failing with the following error:

`Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main`

I will try to expand the sample project to contain everything which is related to detekt in our real projects.

**Comment by lwasyl** [comment]
Generally what I'd do at this point is migrate to `buildSrc` to manage buildscript dependencies and write custom plugin classes that you can easily apply in your modules. It's pretty straightforward (core thing to understand is that everything in `buildSrc` module, including its dependencies, is available in your gradle scripts) and would likely solve this problem faster than figuring out exactly how to make things work currently.
The general idea is that all dependencies from `buildscript` blocks are moved to buildSrc project's build.gradle _regular_ dependencies. All gradle files that you include in build scripts are translated to plugins implemented in buildSrc. This post should be helpful: https://www.stefan-oehme.com/use-buildSrc

**Comment by malejpavouk** [comment]
I can verify that the issue with applying from scriptfile is still valid in 1.2.2. 

The reasoning in behind of our case is very similar. Refactoring of quality related plugins into one build-quality.gradle.kts file.

**Comment by schalkms** [comment]
Since this issue is quite old, I don't think it's worth tracking it. If this issue persists, please feel free to open a new one.
