### ISSUE TITLE
Rule: Safe cast instead of if-else-null

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#197]
Instead of writing:

```kotlin
if (element is KtElement) element else null
```
we can write 
```kotlin
element as? KtElement
```

**Comment by yongzx** [comment]
I would like to contribute.

**Comment by arturbosch** [comment]
Heyho, thx for the interest!

Well are you familiar with the `Visitor`-Pattern? Best way would be to take a look at the existing rules.
There you will find many examples of visitXXX functions.

For this issue you need to visit if statements, check if the `condition` is an `instanceof`-check (`is` or `!is`) and find out if the `then` or `else` part include the identifier used in the `instanceof`-check and `null` for the opposite `then` or `else`.

Give it a try :)

**Comment by yongzx** [comment]
Thanks!
I will give it a try. I will let you know if I meet any problem.

**Comment by yongzx** [comment]
Sorry, after much scrutiny, I couldn't locate any code that resembles `if (element is KtElement) element else null` which I can type cast using `as?`.  Can you give me an example of the `instanceof` statement from the code so I can get a better idea?

I would like to ask if I misunderstand anything. 

> For this issue you need to visit if statements

 does this mean that I need to create a visitxxx if-statement? Because I look through the visitxxx statements, they resemble the form of `if (element is KtElement) do something`.

**Comment by arturbosch** [comment]
Jap, your right, a `visitIfExpressiont` is the entry point for this issue.
It's not that you do a string search for this `pattern` or something. You 'visit' the specific code fragment with a visitor provided by the kotlin compiler.

We first analyze the 'pattern'. We have a IfExpression. A IfExpression has a condition (Expression) and a then- and an else-clause. Both are `Expressions` again. The condition must be a `KtIsExpression`. Now we look at the identifier `element` and the type `KtElement`. This two things must be used in the then- and else-clauses.

Hope that helps a bit.
