### ISSUE TITLE
Gradle plugin fails with Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.12

### ISSUE THREAD

**Issue by pkubowicz** [arturbosch/detekt#2146]
## Expected Behavior
I can run Detekt on a multi-project build

## Observed Behavior
Build fails with:
```
> Task :core:detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:detekt'.
> Could not resolve all files for configuration ':core:detekt'.
   > Could not find org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.12.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.6.12/kotlinx-html-jvm-0.6.12.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :core > io.gitlab.arturbosch.detekt:detekt-cli:1.2.0
```

## Steps to Reproduce
Example build.gradle:
```groovy
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.61' apply false
    id "io.gitlab.arturbosch.detekt" version "1.2.0" apply false
}

subprojects {
    apply plugin: 'kotlin'
    apply plugin: "io.gitlab.arturbosch.detekt"

    repositories {
        mavenCentral()
    }
}
```

## Context
I can run Detekt if I downgrade it to 1.1.0.

## Your Environment

* Version of detekt used: 1.2.0
* Version of Gradle used (if applicable): 6.0.1
* Operating System and version: Kubuntu 19.10
* Link to your project (if it's a public repository):

**Comment by arturbosch** [comment]
Try adding `jcenter` to the repositories and it should work.

@schalkms @BraisGabin kotlinx.html does not seem to be hosted at maven central -> https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-html-jvm?repo=jcenter 
this will lead to followup support issues which request to be compatible with maven central :/

**Comment by pkubowicz** [comment]
Yes, jcenter helps.

**Comment by schalkms** [comment]
I'm not sure how much effort we need for migrating back to our own **HTML DSL**.

**Comment by BraisGabin** [comment]
https://github.com/Kotlin/kotlinx.html/issues/81 and https://github.com/Kotlin/kotlinx.html/issues/116 points the same.

We could go back to a custom dsl... but it would be kind of painfull. I moved to kotlinx.html because it was difficult to mantain and extend the current one. And I don't know if it have sense for us to expend time building an maintaing a custom html dsl.

**Comment by 3flex** [comment]
We should stick with kotlinx.

Jcenter has problems but Gradle since 5.1 has tools to control which dependencies are pulled from certain repos which I think is a reasonable compromise. Users can restrict jcenter to pull only kotlinx dependencies for example.

https://docs.gradle.org/5.1/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies

**Comment by BraisGabin** [comment]
And if you *really* don't want jCenter you can remove the html dependency and disable the html report. It should work. Or download kotlinx.html jar and add it to your libs... None of my options are perfect but we can do very little about the host of kotlix.html.

**Comment by pkubowicz** [comment]
I think it would be beneficial to add a note to https://github.com/arturbosch/detekt#with-gradle explaining that jCenter is important and that this is due to kotlinx-html dependency.

**Comment by schalkms** [comment]
Closed by https://github.com/arturbosch/detekt/commit/a754335bc9fea42d13cbb26adbeddab68b84ebe5
