### ISSUE TITLE
Add jvmTarget change into documentation

### ISSUE THREAD

**Issue by imanushin** [arturbosch/detekt#2157]
## Expected Behavior
Extend documentation and show ability to put JVM target into task

## Current Behavior
At my project (which is built for JVM 11) the following error is appeared: 
```
error: cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
```

## Context
This happens in case, when Detect thinks, that project is built for default JVM (e.g. 1.6), however actual version is later one. It means, that Kapt compiler tries to do unsupported operations.

## Solution

Add the following line into ```gradle.build.kts```:

```
tasks {
    withType<Detekt> {
        this.jvmTarget = "11"
    }
}
```

**Comment by schalkms** [comment]
Thanks for providing a fix for the mentioned problem!
I think this fix should be added to the docs on detekt's homepage, in order to have this persisted.
@imanushin Would you mind submitting a PR that add's this snippet and the fantastic problem description you gave to detekt's **Getting started** guide? That would be highly appreciated.

**Comment by imanushin** [comment]
@schalkms , agree. I will try to do PR at the nearest weekend.
