### ISSUE TITLE
Think about removing the issue weights feature for build failure thresholds

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#2272]
Further discussion from #2266

## Expected Behavior
Remove the extra complexity.

## Current Behavior
Issue kinds can be weighted to influence the build failure threshold higher than other issues.
Do we want to maintain this feature?
The only usecase I see is to have specific rules printed on the console as a reminder to remove them someday.

## Context
#2266

**Comment by schalkms** [comment]
I think we shouldn’t remove this. We also have a similar unresolved feature in #533.

**Comment by Mkohm** [comment]
I am using this feature! 

I am developing an [extension to detekt](https://github.com/Mkohm/detekt-hint) that focuses on detection of programming principle violations. Because these principles are hard to detect with low false-positive rate i need a way of spotting them, but without breaking the build and creating unnecessary noise.

**Comment by schalkms** [comment]
Nice project @Mkohm 
I gave it star. It looks really promising.
It’s always great to see such efforts!!

**Comment by schalkms** [comment]
Closed because I think this really provides value to the user.
