### ISSUE TITLE
Android Sample Project?

### ISSUE THREAD

**Issue by cortinico** [arturbosch/detekt#2310]
I noticed that we're currently having a raising number of question related to usage of Detekt with type & symbol resolution. Apparently the configuration is not trivial (#2292), especially if you're dealing with an Android project.

I assume a significant amount of our users are actually Android Developers (do we have stats?). I think it would be beneficial to have a detekt/detekt-android-sample project to use as a template repo for developers that are planning to Detekt in an Android project.

I wanted to get your point of views on this.

## Context
See #2292
Potentially related to #1169

**Comment by schalkms** [comment]
Good point!
This is part of #2259. We will provide the code snippet on the homepage.
I think this one is a duplicate. If you have suggestions on how to improve the documentation, please  add a comment in #2259.

**Comment by cortinico** [comment]
> This is part of #2259. We will provide the code snippet on the homepage.

That's really great.

My point was more about having an actually project and keeping its Detekt version up to date. We keep on having Gradle snippets on the docs that are deprecated (#2303 #2311). Having an actual configured working project (that is not the detekt repo itself) will give higher confidence to the users.

We could potentially have it also as a [template repo](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by schalkms** [comment]
We are happy to link such a project in the readme or on the homepage. However, you can expect a developer familiar with Gradle to copy code from the docs to the corresponding file. I think it’s time consuming to have projects for all platforms that you need to maintain and adapt.

Once again, we are happy to link every blog post or repo peovided by the community in our docs. We also help to polish them if necessary.

I’m closing this due to the mentioned reasons.
