### ISSUE TITLE
Add logging/regex exceptions to MaximumLineLength

### ISSUE THREAD

**Issue by mrf7** [arturbosch/detekt#2511]
## Expected Behavior of the rule
When using the MaximumLineLength rule I don't really care if logging lines go over the max line length since it's mostly just a hardcoded string. Forcing calls to logging libraries to be broken into a multi line argument list adds unnecessary noise to the code. This would have to work generically for different logging frameworks. 

## Context
Allowing single line logs would simplify code that contains long Log statements.

**Comment by schalkms** [comment]
Thanks for your feedback!
You could use something like this. Detekt also has several `report` statements written like this.

```kotlin
Logger.log("A really long"
    + " line")
```

The following snippet is an example taken from detekt's code base. This doesn't add any noise to the code.

https://github.com/arturbosch/detekt/blob/38c54c80d67b92252d1a2b2e40f03cb8058ebd48/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MagicNumber.kt#L90-L94

The second option is to **suppress** such issues. 
Moreover you could deactivate this rule altogether, if you don't find it useful for your codebase.

You could also try to extend detekt's *native* [MaxLineLength](https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/MaxLineLength.kt) rule with the help of a domain-specific rule. Take a look [here](https://arturbosch.github.io/detekt/extensions.html#custom-rulesets) if you want to more about domain-specific rules.

> This would have to work generically for different logging frameworks.

As a word of warning, you will have trouble achieving this for all possible logging frameworks, since there are so many out there. It's not that easy to decide, whether a call is a logging call or not. You need type and symbol solving to achieve this. You have to list all logging frameworks that you use and declare it. A generic solution won't work here, unfortunately.

Since `MaximumLineLength` is a [ktlint](https://github.com/pinterest/ktlint) rule, you might want to open an issue there and see what they think about your suggestion. Detekt just provides a wrapper over the  `MaximumLineLength` rule.

**Comment by schalkms** [comment]
Since this requirement is very domain-specific and thus out of scope for detekt and due to the fact that there is actually an existing solution mentioned above, this issue will be closed.
