### ISSUE TITLE
[New Rule] Support dead code detection(non-private class/member included)

### ISSUE THREAD

**Issue by jaychang0917** [arturbosch/detekt#2573]
Currently, we have `UnusedPrivateClass` and `UnusedPrivateMember` rules to detect dead code, but that only check **private** class/member. How about to support non-private ones?

## Expected Behavior of the rule
Similar to `UnusedPrivateClass` and `UnusedPrivateMember`, but detect unused non-private class/member.

## Context
The use case is we don't want any dead code exist in the codebase, and warn developer if there is any dead code to check in.

Thanks!

**Comment by schalkms** [comment]
Thanks for the great suggestion, Jay. I also think that this feature would be of great use for the user. We already got this suggestion once in issue #2229.
Issue #1915 tracks this feature, since it needs type and symbol solving to be realized. If you like, feel free to subscribe to this issue. Please note that we could really use a helping hand for the realization part here. If you have questions, don't hesitate to ask.
