### ISSUE TITLE
Run Detekt for the whole project in one task

### ISSUE THREAD

**Issue by bartek-wesolowski** [arturbosch/detekt#2593]
This feature request is inspired by the following article:
https://madhead.me/posts/detekt-faster/

If you run `./gradlew detekt` then it runs Detekt for each subproject separately. It generates separate reports for all modules and there's an overhead of running multiple Gradle tasks.

Couldn't there be a task like `detektAll` for checking the whole project and generating a single report?

**Comment by BraisGabin** [comment]
About the speed: that problem was fixed. Use 1.7.x and you will see. More details at #2035 

About running detekt all in once: I see problems related with type solving. Each module has different classpath so running all at once can be tricky. Give official support to that doesn't seem a good option. 

And you can follow this issue to know about the consolidated reports: #1295

**Comment by schalkms** [comment]
As Brais mentioned, the performance issue was fixed. Regarding the consolidated report  please follow the discussion in the linked issue. Every helping hand counts. 🙂
