### ISSUE TITLE
MissingCases

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#269]
A rule that detekts missing cases.

This could be useful when using `when` with enums or sealed classes.

[ErrorProne reference](https://github.com/google/error-prone/blob/master/docs/bugpattern/MissingCasesInEnumSwitch.md).

**Comment by arturbosch** [comment]
This one needs type resolution.

**Comment by 3flex** [comment]
Started looking at this now we have type & symbol resolution - missing cases throw a compiler error, so there doesn't seem to be much point adding a check to detekt as well? Compiler warnings can be reimplemented in detekt so it the rule can be enabled or disabled, but I think errors need to be reimplemented since the code won't compile anyway.

```kotlin
    enum class WhenTest {
        RED,
        YELLOW,
        BLUE
    }

    val whenTestElement = WhenTest.BLUE

    val something = when(whenTestElement) {
        WhenTest.BLUE -> "blue"
    }
```

> e: path\to\file\MissingWhenStatement.kt: (40, 21): 'when' expression must be exhaustive, add necessary 'RED', 'YELLOW' branches or 'else' branch instead
