### ISSUE TITLE
Add code coverage analysis to the CI process

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#301]
The idea here is to integrate a code coverage tool into detekt's CI process to measure the degree to which the source code of this repo is executed.
A tool which might be used for this is **Jacoco**.

**Comment by Mauin** [comment]
Can we either give this issue more details or close it?

**Comment by schalkms** [comment]
I updated this issue with more details. This shouldn't be closed.

**Comment by 3flex** [comment]
Should have a PR for this later today - I have added JaCoCo and it's uploading to Codecov on my own branch and seems to be working pretty well, though JaCoCo has some existing issues with Kotlin code so there will definitely be some false positives with missed/partially hit lines (particularly with inline functions, though that may be fixed in JaCoCo 0.8.3). Will have to track updates to that tool closely to improve the quality of the report.

Just need to add support for checking & uploading coverage for the Gradle plugin as well then I'll submit.

**Comment by schalkms** [comment]
@3flex wow, that's great. Some month ago I checked the coverage locally with IntelliJ and added some tests. At least the unit test coverage is fine, but there's more work necessary. I am thinking of integration tests here.
