### ISSUE TITLE
Change threshold definition in detekt

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#313]
As mentioned by @schalkms in #300 detekt's definition of a `threshold` is: Every value which is greater than the threshold should be flagged eg. for threshold 3: 
  - value 3 will not get flagged as 3 is not > 3
  - value 4 will get flagged as 4 > 3

Other tools uses a value-inclusive-threshold: Every value which greater than or equals the threshold should get flagged eg. for threshold 3:
  - value 3 and 4 get flagged as 3|4 >= 3 

Discuss and vote :)

**Comment by arturbosch** [comment]
Leave the threshold as it is now. Every value > threshold get flagged.

**Comment by arturbosch** [comment]
Change to every value >= threshold get flagged.

**Comment by vanniktech** [comment]
I have no preference since even having one warning / error fails my builds. Naturally if the threshold is 3, I'd expect to only fail on 4.

If we look at the definition:

> the magnitude or intensity that must be exceeded for a certain reaction, phenomenon, result, or condition to occur or be manifested.

It uses the word `exceeded` which would mean 3/3 okay 4/3 not.

**Comment by schalkms** [comment]
>= 
for me

**Comment by sschuberth** [comment]
For me the most natural semantics (independently of whether you call it "threshold" or something else) would be to specify "the maximum number of accepted defects". This is nice because in a project where you continuously reduce the number of defects, the current threshold would show the renaming number of defects to address. I believe this is more natural than specifying the number of defects starting from which a build is supposed to fail.

So, how about a compromise and keep the `failThreshold` keyword, but also introduce a `maxDefects` keyword, and not allow to specify both?

**Comment by arturbosch** [comment]
First: I will change the threshold definition to `value >= threshold` like it is used in other tools like [pmd](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/CyclomaticComplexityRule.java)

Second: Remove `warningThreshold` and `failThreshold` and introduce `maxDefects`. What do you think about this? Anyone ever used this for warnings?

**Comment by Mauin** [comment]
Sounds good. I haven't used either thresholds much so don't have a strong opinion on it.

**Comment by arturbosch** [comment]
I think this is done for now :).
