### ISSUE TITLE
[Feature Request] - Do not download dependencies during runtime

### ISSUE THREAD

**Issue by jaredsburrows** [arturbosch/detekt#363]
My current project is using `1.0.0.RC3`, see https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/versions.gradle.kts#L35.

Now I have a build failure because the latest dependencies were download during runtime: https://travis-ci.org/jaredsburrows/android-gif-example/builds/271003620#L2876.

**Comment by arturbosch** [comment]
We had a discussion about this behavior somewhere I can't link to now. The main take away was: if you want to stay on the same version specify the `version` property inside the deteKt extension (it's ok that the maintainer need to do extra work for CI). If you want to stay up to date, do not specify it. The new policy is that no new rules get enabled by default. This case happened because we refactored some old rule...

If there is more demand we still can change the default update behavior.

**Comment by jaredsburrows** [comment]
Alright. I will be forced to use "version = 1.0.0RC3" for now.

For example, here https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/versions.gradle.kts#L35 and https://github.com/jaredsburrows/android-gif-example/blob/master/gradle/quality.gradle#L49.

This is the Kotlin DSL, it might be easier to share external properties in the normal Groovy DSL but either way we have to specify the version twice.

**Comment by 3flex** [comment]
I vote in favour of changing the current behaviour.

The behaviour of this plugin is different to most other Gradle plugins so its behaviour is surprising - the checkstyle, PMD and FindBugs Gradle plugins for example all have a static, default version specified by Gradle. Though new Gradle versions do change these default versions without the user explicitly setting them, it would only change because the user has upgraded Gradle. It doesn't suddenly use a new version just because a new checkstyle version is released.

I expect that if I specify

```
plugins {
    id("io.gitlab.arturbosch.detekt").version("1.0.0.[version]")
}
```

then [version] is the version of the plugin that will run. This also makes builds non-deterministic for the same reason that using `+` for a version in build dependencies is a [bad idea](http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/).

**Comment by mkobit** [comment]
It also can lead to undesirable behavior if `SNAPSHOT` type releases because those can be selected with the dynamic versioning. The JUnit 5 project went through this as well (in https://github.com/junit-team/junit5/issues/576) and switched to a default version.

**Comment by arturbosch** [comment]
I guess we will change it then.
If I remember correctly my problem was that I had to hard code the detekt version inside the grade plugin. 
When forgetting to increment that version the release is kinda broken. 

I could write a task which is triggered before `publishPlugins` which creates a resource with a version property which is used inside the gradle plugin to for version resolving. Any other ideas or comments about this?

**Comment by jaredsburrows** [comment]
You have to manually bump the version in the gradle.properties file now.
Just use the same variable for version.

**Comment by Mauin** [comment]
Closing this issue as the Gradle Plugin now uses a hardcoded default version of detekt itself.
