### ISSUE TITLE
Rules: Static Application Security Testing

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#384]
In my opinion this would be a nice feature.

The **Open Web Application Security Project** lists various tools with security based rules.
reference:
https://www.owasp.org/index.php/Source_Code_Analysis_Tools

**Comment by arturbosch** [comment]
Interesting, what kind of security flaws to you have in mind.

**Comment by schalkms** [comment]
Actually, there are many security flaws. Just to mention a few
- Weak hashing
- Pseudo random
- SQL injection
- XSS

**Comment by thetric** [comment]
Spotbugs (formally known as Findbugs) has [Find Security Bugs](https://github.com/find-sec-bugs/find-sec-bugs) which "can detect 127 different vulnerability types with over 806 unique API signatures", see [this overview](https://find-sec-bugs.github.io/bugs.htm). This is something I miss in Detekt.

**Comment by schalkms** [comment]
Good point

**Comment by arturbosch** [comment]
Findbugs should also work with kotlin and detect these patterns? Maybe the linenumbers are off..

**Comment by thetric** [comment]
> Findbugs should also work with kotlin and detect these patterns?

Yes, Spotbugs can _now_ detect these patterns. Until recently the Spotbugs Gradle plugin wasn't able to analyze Kotlin code due to a breaking change in Gradle 4.0, which is fixed in release 1.6.2 (see https://github.com/spotbugs/spotbugs-gradle-plugin/pull/12).

Some short tests are promising, I didn't notice any bad source mapping. Although when using Spotbugs to analyze Kotlin code I'd recommend disabling the pattern categories BAD_PRACTICE, CORRECTNESS, I18N, MT_CORRECTNESS, NOISE, PERFORMANCE and STYLE as they mostly concern the Kotlin-generated bytecode, not the actual source code.

@schalkms do you think that it is still necessary to re-implement these rules for Detekt? FindSecBugs seems to [cover your suggestions](https://find-sec-bugs.github.io/bugs.htm)

**Comment by vanniktech** [comment]
We shouldn't reimplement those if they work with findbugs.

**Comment by schalkms** [comment]
No. There is no need to reimplement the same functionality.
I am closing this issue.
