### ISSUE TITLE
autoCorrect no longer works after format module removed.

### ISSUE THREAD

**Issue by joshallenit** [arturbosch/detekt#543]
Hi,

autoCorrect no longer works for me after upgrading to RC5-3. I think that it's because the format module was removed in RC5. UnusedImport and sometimes whiteSpace is the only thing I used it for and without autoCorrect it's an annoying lint failure.

Thanks,
Josh

**Comment by arturbosch** [comment]
Hi,
thats right. 

I removed the format module in order to disable autoCorrect because I think meddling with strangers code is more trouble than it is worth.
The tool ktlint already offers formatting and autoCorrect. We were doing the same work here. From RC5 on we stopped the formatting effort. Still the ability to `autoCorrect` remains in detekt -> you can write your custom rules. 

If you are interested in custom formatting rules, take a look at the `ktlint-over-detekt` module which I just now hacked together (https://github.com/arturbosch/detekt/tree/integrate-ktlint, UnusedImport rule -> github.com/arturbosch/detekt/blob/integrate-ktlint/ktlint-over-detekt/src/main/kotlin/io/gitlab/arturbosch/detekt/ktlint/UnusedImport.ktodebeat.co/open-source/)

**Comment by joshallenit** [comment]
Thanks, I'm using ktlint for the auto correct and it works well.

**Comment by Mauin** [comment]
Closing this as the issue seems to be solved. Feel free to re-open this if there are more questions.
