### ISSUE TITLE
Method for printing out all AST nodes in a file

### ISSUE THREAD

**Issue by Nevvea7** [arturbosch/detekt#553]
I was watching a [KotlinConf video](https://youtu.be/p8yX5-lPS6o?t=23m57s) and saw they have a function that prints out all the names of the AST nodes in a file ([implementation](https://github.com/JetBrains/uast/blob/951b7e299a6eb604599ef5c8e5521bcbf5345ea6/uast-common/src/org/jetbrains/uast/qualifiedUtils.kt#L164)). As a AST rookie I find this very helpful because right now I basically trial and error to find the correct `visit` method to use. I didn't find a function like this in detekt so just wondering if it's already a thing, or if not do you think it makes sense to implement it.

Thanks!

**Comment by 3flex** [comment]
I came across [PSI Viewer](https://plugins.jetbrains.com/plugin/227-psiviewer) which shows the PSI structure in a tree view in IntelliJ, and also shows the type of the PSI element which you can map back to appropriate `visit` method.

detekt isn't using UAST so the PSI viewer will definitely be more useful than anything related to UAST. Since detekt focuses only on Kotlin files, and the UAST is the "Universal" AST structure and could be applied to many JVM languages, it's probably not beneficial for detekt to migrate.

**Comment by arturbosch** [comment]
When I started experimenting with the AST, I used this two visitors (see commit dbab8e2ccf86141f79c064e37e6e5389bb52677e):

```kotlin
class ElementPrinter : Rule("ElementPrinter") {

	override fun visitElement(element: PsiElement) {
		element.print()
	}

}
```

```kotlin
class TokenPrinter : TokenRule("TokenPrinter") {

	override fun procedure(node: ASTNode) {
		node.print()
	}

}
```

The Psi Viewer is a better TokenPrinter ;)

**Comment by Nevvea7** [comment]
icic, thank you!
