### ISSUE TITLE
The Gradle plugin tasks should extend SourceTask

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#580]
Taking a note from how Gradle's own code quality plugins are done, the Detekt Gradle tasks should inherit from [`SourceTask`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceTask.html), a specialised subclass of `DefaultTask` (what it's using now). The validation tasks (e.g., `detektCheck`) should also implement `VerificationTask` and `Reporting<DetektReports>` (where `DetektReports` extends `ReportContainer<SingleFileReport>`) to align to the built-in Gradle Checkstyle/PMD/Findbugs/... plugins.

Thoughts?

**Comment by 3flex** [comment]
I 100% agree, and had started doing a bit of work to modernise the Gradle integration to better align with the code quality plugins. I put it on hold because I'm working on making detekt work as a Kotlin compiler plugin (so it hooks into the compilation process in a similar way to Error Prone). Making this work requires substantial changes to the Gradle integration. I should have something to share in a day or two, I was actually working on the Gradle integration part yesterday.

It probably makes sense to wait for that before changing the DSL and updating the Gradle plugin internals, because there might be other internal changes to be made to support that.

**Comment by 3flex** [comment]
A couple of other interesting classes: CodeQualityExtension, VerificationTask, Reporting. AbstractCodeQualityPlugin is probably useful but is in a package marked "internal" so probably shouldn't be used.

**Comment by arturbosch** [comment]
Yep, agree both @rock3r @3flex . This issue is linked to #540 and #542 . Rework is planned after @3flex 's work.

**Comment by arturbosch** [comment]
I do think `AbstractCodeQualityPlugin` is the way to go even if it is internal. I mean what could possible go wrong?
But I do not see the benefit implemening any of this classes yet ...
I have to override so many methods and the api is like ''I Have No Idea What I'm Doing'' ...

**Comment by Mauin** [comment]
Closing this as the reworked plugin has been merged.
