### ISSUE TITLE
Allow --input to handle multiple paths

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#605]
Required for #485 and https://github.com/arturbosch/detekt/issues/540#issuecomment-343890872.

Right now `--input` only takes a single file or directory, but a Gradle source set can consist of multiple directories. detekt CLI needs to change so `--input` can take a `;` delimited string of multiple paths and handle appropriately.

As mentioned in https://github.com/arturbosch/detekt/pull/485#issuecomment-351212020 I made an attempt at this, but there are impacts throughout the code. It's better if someone more familiar with the path handling part of the codebase makes this change.

**Comment by arturbosch** [comment]
Just analyzed what we have to change ...:
- `KtTreeCompiler` needs a path, so we need could change the `run` method to get a path instead of storing it as a field. This requires to create a KtCompiler on demand.
- `Detektor` class needs a path to resolve the relative paths and write back the AST to a file if it gets modified
- `ProcessingSettings` needs a `List<Path>`
- `Args` class needs to return a `List<Path>`

**Comment by Mauin** [comment]
Closing via #619
