### ISSUE TITLE
Homebrew formula for installing detekt cli

### ISSUE THREAD

**Issue by benjamincassidy** [arturbosch/detekt#748]
I've created a Homebrew formula for installing detekt cli on OS X.

https://github.com/Homebrew/homebrew-core/pull/24225

**Comment by schalkms** [comment]
That’s a good idea. However, as mentioned in the linked PR, detekt v1 is not available (yet). I just keep this open and create a notification when it’s done.

**Comment by benjamincassidy** [comment]
What's the timeline for a v1 release? I really dig Detekt. Thanks!

**Comment by arturbosch** [comment]
It will come sooner than later :)

**Comment by benjamincassidy** [comment]
Thanks, I'll keep an eye out and resubmit the formula to Homebrew when it's released.

**Comment by schalkms** [comment]
Since detekt can now be downloaded from every major source repository in the Java world, homebrew has a pretty low priority. The community can of course submit detekt to other source repositories as well.

**Comment by TamasBarta** [comment]
Hi,
Can you help me with this? I know Brew, and Sdkman, none of which has the CLI version of Detekt. How can I install Detekt, if I want to avoid all the bloat of Gradle? (On CI, I'll use that for sure, but for dev installs, where I want to lint many projects without integration, it's bloat)
The Getting Started's CLI part in the readme is quite ugly, I think we can agree on that. I'm not that comfortable to include it in a team guide where possible even Windows guys participate.
So my question is that is Detekt available in a cross platform or any platform specific repo, where I can say: "`mytool install detekt`", and have it included in path as `detekt`? Maybe Maven repos can be used like that, but I don't know how that is possible.
Thanks!

**Comment by schalkms** [comment]
>  I know Brew, and Sdkman, none of which has the CLI version of Detekt. 

You could upload the detekt sources to brew. The original poster's PR was rejected, because detekt was in the RC phase back then and the brew team doesn't allow release candidate versions included in brew.

> How can I install Detekt, if I want to avoid all the bloat of Gradle?

You could use the CLI or the unofficial detekt [Maven plugin](https://github.com/Ozsie/detekt-maven-plugin).

> The Getting Started's CLI part in the readme is quite ugly, I think we can agree on that.

What do you think can be improved? What do you find missing there (for your task at hand)?

> How can I install Detekt, if I want to avoid all the bloat of Gradle?

You just need Gradle for building the detekt:CLI project by yourself.
You could then upload the .jar to your companies repo, where every developer can download it then. The `detekt-config.yml` file can for instance be checked in your Git repo.

-----
Does this answer your questions?

**Comment by TamasBarta** [comment]
Hi @schalkms,

Thanks for your answer. Probably uploading to Brew would be the best solution, I just worry about its maintaining. Mostly I'm a Linux user, so there's no guarantee that I can update it with new versions of Detekt.
The Maven plugin also is a plugin for a task runner, which I don't see a reason to use when I just want to quickly clone a project, and scan it without setting its task runner up for Detekt.
What I meant by ugly (I hope I wasn't too harsh with that comment) is that it's hard to use it in an install/setup script. I have to type in the version in one of the four lines explicitly, which is not the case with Brew, which also can update Detekt. This also does not result in a `detekt` alias on my system to run Java with a specific jar and passing in the arguments.

So technically you answered my question, but downloading a jar from a URL with the version hardcoded in it, manually putting it _somewhere_ and then aliasing it manually sounds complex. What I'm not aware of, and wanted to ask if it exists, is something like npm and cargo does: you can globally install the package, and the package can expose commands, which are then in the path form then on. 

I'm okay with creating the formula for Brew (I have to learn that first though), but I'm uncertain about its maintenance.

**Comment by schalkms** [comment]
Sorry for responding so late.

> Mostly I'm a Linux user, so there's no guarantee that I can update it with new versions of Detekt.

I think that's ok. Somebody from the community will probably update the versions.
We as the detekt team can't support every potential package manager.
I hope that this is understandable.
We focus on the most common use cases that are inline with the majority of detekt's users.

> What I meant by ugly (I hope I wasn't too harsh with that comment) is that it's hard to use it in an install/setup script.

No worries. We try to improve the documentation iteratively.
So we also rely on user feedback in order to achieve that.
Regarding the scripting stuff, I can say that some guys integrated detekt into their commit pipeline with the help of a pre-commit hook.
It might be worthwhile to check that out. [Reference](https://medium.com/binar-academy/android-kotlin-code-quality-check-using-detekt-and-git-hooks-pre-push-mac-and-linux-556c111bc71b)

----

Regarding the last question, it should be possible to do that. However, I can't point you to a definitive guide, since I haven't done that for .jars.
