### ISSUE TITLE
[bug]UnsafeCallOnNullableType

### ISSUE THREAD

**Issue by cyw3** [arturbosch/detekt#940]
**mOnTemplateSelectListener** have been judged before being used, but detekt still think it is a problem.
![image](https://user-images.githubusercontent.com/11549103/40914543-318ae2c0-682b-11e8-8ec4-c762f4531ba6.png)

**Comment by LanderlYoung** [comment]
this is not a bug

**Comment by cyw3** [comment]
@LanderlYoung Why?

**Comment by arturbosch** [comment]
For this rule we are just using the intellij util method to detect unsafe casts. I'm pretty sure that intellij itself will report this case because `mOnTemplateSelectListener` is a field which could change when using multiple threads.
How about refactoring the code to use `mOnTemplateSelectListener?.call(...)`?

**Comment by LanderlYoung** [comment]
@arturbosch thanks, I think this issue should be closed. @cyw3
